name: Spider

on: [push]
  # push:
  #   tags:
  #   - 'v*' # i.e. v1.0, v2o.15.10

# on: 
#   schedule:
#     - cron:  '*/30 * * * *' # 8am daily. Ref https://crontab.guru/examples.html

jobs:
  spider:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: main

    - name: 'Set up Python'
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Run a single-line script
      run: |
        pip install pandas beautifulsoup4
        mkdir datas
        python ./cz_simples_text.py
#        scrapy crawl recordsbot -o data.csv

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: ./datas
        retention-days: 15
